#ifndef TEMP_SENSOR_CFG_H
#define TEMP_SENSOR_CFG_H

#define TEMP_SENSOR_REVISION_A 0x0000
#define TEMP_SENSOR_REVISION_B 0x0001

#define TEMP_SENSOR_REVISION_1_PRESCALER 1
#define TEMP_SENSOR_REVISION_2_PRESCALER 10

#define TEMP_SENSOR_SAMPLE_COUNT 200
#define TEMP_SENSOR_REVISION TEMP_SENSOR_REVISION_A
#endif /* TEMP_SENSOR_CFG_H */
