#ifndef TEMP_SENSOR_CFG_H
#define TEMP_SENSOR_CFG_H

#define TEMP_SENSOR_REVISION_A     0x0000
#define TEMP_SENSOR_REVISION_B     0x0001
#define TEMP_SENSOR_REVISION_EMPTY 0xFFFF

#define TEMP_SENSOR_REVISION_A_PRESCALER 1
#define TEMP_SENSOR_REVISION_B_PRESCALER 10

#define TEMP_SENSOR_SAMPLE_COUNT 200

#define TEMP_SENSOR_WARNING_LOWER_THRESHOLD 5
#define TEMP_SENSOR_WARNING_UPPER_THRESHOLD 85
#define TEMP_SENSOR_CRITICAL_LOWER_THRESHOLD 105

#define TEMP_SENSOR_HYSTERESIS_VALUE 2

#endif /* TEMP_SENSOR_CFG_H */
